name=input("Enter name:")
rollno=int(input("Enter roll no:"))
mark=float(input("Enter Marks:"))
mobno=int(input("Enter mobile no:"))
age=int(input("Enter Age"))
dept=input("Enter Department:")

print("-----Student Info-----")
print("Name:",name)
print("Roll no:",rollno)
print("Marks:",mark)
print("Mobile no:",mobno)
print("Age:",age)
print("Department:",dept)
